---
#
# ######################### #
# playbook-master-setup.yml #
# ######################### #
#
# This playbook will take a master node that has undergone the basic setup applied
# in the playbook-nodes-setup.yml and makes a single node the kubernetes master.
#
# The prerequisites are
#
#   - the playbook-all-nodes.yml has been run
#   - (either) there has been no attempt to make this node a master
#   - (or)     previous attempts have been reset with playbook-master-reset.yml
#
# Once you've checked that the master configuration you can then procedd to join
# worker nodes to the cluster with the playbook-worker-join.yml
#

- hosts: master
  vars_files:
    - ./vars/variables.yml
  become: true
  name: Setup control plane and make kubectl talk to cluster
  tasks:

  - name: Removing config.toml to allow kubeadm to work
    ansible.builtin.file:
      path: /etc/containerd/config.toml
      state: absent
    
  - name: Initialize the Kubernetes control plane using kubeadm
    become: true
#    command: kubeadm init --control-plane-endpoint={{ k8s_master_hostname }} --apiserver-advertise-address="192.168.0.47" --apiserver-cert-extra-sans="192.168.0.47" --node-name=inca1
    command: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket /run/cri-dockerd.sock
    register: kubeadm_init_output

  - name: Store the Logs generated by the kubeadm cluster initialize command
    local_action: copy content={{ kubeadm_init_output.stdout }} dest=kubeadm-init-output.log backup=yes
    become: false

  - name: Create the .kube directory to hold the kubectl configuration
    become: false
    file:
      path: /home/{{ node_username }}/.kube
      state: directory
      owner: {{ node_username }}
      group: docker
      mode: 0755

  - name: Copy the kubectl configuration for the local user
    become: true
    command: "{{ item }}"
    with_items:
     - cp -i /etc/kubernetes/admin.conf /home/{{ node_username }}/.kube/config
     - chown {{ node_username }}:docker /home/{{ node_username }}/.kube/config

  - name: Fetch kubectl config for laptop (ansible host) to use
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: kubectl-configuration.yml
      backup: yes
      flat: yes

  - name: Copy to local user so laptop kubectl connects to cluster
    become: false
    copy:
      src: kubectl-configuration.yml
      dest: ~/.kube/config
      backup: yes
    delegate_to: localhost

#  - name: Install calico pod networking using kubectl on the master
#    become: false
#    command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
