---
#
# ######################## #
# playbook-worker-join.yml #
# ######################## #
#
# This playbook will attempt to join any worker node into the cluster being
# controlled by the master node. The prerequisites are
#
#   - the playbook-base-install.yml has been run for all nodes
#   - the master was successfully created with playbook-master-setup.yml
#   - (either) the worker/s have never attempted to join a cluster
#   - (or)     the worker/s have been reset with playbook-worker-reset.yml
#
# The master node is used to extract a join command which is then executed
# on the worker/s.
#
# A pre-check is to ssh into the master and validate that this command
# correctly produces a join command.
#
#    kubeadm token create --print-join-command
#

- hosts: worker
  vars_files:
    - ./vars/variables.yml
  name: Get each worker node to join the kubernetes cluster
  tasks:

  - name: Run kubeadm reset before init.
    become: true
    command: kubeadm reset --force --cri-socket /run/cri-dockerd.sock

  - name: Join the worker node to the kubernetes cluster
    become: true
    command: "kubeadm join {{ master_ip_address }}:6443 --token {{ kubeadm_join_token }}  --cri-socket /run/cri-dockerd.sock --discovery-token-unsafe-skip-ca-verification"
